version: '3'
services:
  mapnik:
    image: "jupytepide/tilestache-mapnik"
    container_name: jupytepide-mapnik
    ports:
     - "32798:22"
     - "32799:9001"
     - "32800:80"
    volumes:
     - /opt/jupytepide/mapnik-data:/etc/tilestache
