version: '3'
services:
  mapnik:
    image: "reg.jupyteo.com/mapnik-flask:1.3.6"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupytepide-mapnik
    ports:
    - "9443:80"
    volumes:
    - /opt/var/mapnik:/opt/var/mapnik