version: "3"
services:
  jupyteo-hub:
    # build an image with SwarmSpawner and our jupyterhub_config.py
    env_file:
      - .env
      - secrets/oauth.env
    build:
      context: ../
      dockerfile: ./hub/Dockerfile
    image: "reg.jupyteo.com/jupyterhub:0.9.4-2.0.0"
    container_name: jupyteo-hub
    # mount the docker socket
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - ../hub/jupyterhub_config.py:/tmp/jupyterhub_config.py
    - ../hub/run-from-compose.sh:/run-from-compose.sh
    - /opt/data/priv/:/opt/data/priv/
    - /opt/var/:/opt/var/
    networks:
      - jupyteo-net
    # This is necessary to prevent the singleton hub from using its service number as its hostname
    ports:
    - "8000:8000"
    hostname: jupyteo-hub
    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_SPAWN_NOTEBOOK_IMAGE: ${DOCKER_SPAWN_NOTEBOOK_IMAGE}
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      SPAWN_USER: ${SPAWN_USER}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
    command: sh /run-from-compose.sh

  nginx:
    env_file: .env
    image: linuxserver/letsencrypt
    container_name: jupyteo-nginx
    hostname: jupyteo-nginx
    networks:
      - jupyteo-net
    # expose the proxy to the world
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_volume:/config"
    - /home/daniel/jupyteo-dev/swarm/letsencrypt_container_nginx.conf:/config/nginx/site-confs/default
    environment:
      EMAIL: ${EMAIL}
      URL: ${URL}
      SUBDOMAINS: reg,cloud,demo,try,notebooks,notebook,jupyter
      ONLY_SUBDOMAINS: 'true'
      EXTRA_DOMAINS: reg.jupyteo.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
    cap_add:
    - NET_ADMIN

  postgis:
    image: kartoza/postgis:9.6-2.4
    container_name: jupyteo-postgis
    networks:
      - jupyteo-net
    volumes:
    - postgis-db-data:/var/lib/postgresql
    ports:
    - "25432:5432"
    env_file:
    - postgis.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
    restart: on-failure
    healthcheck:
      test: "exit 0"

  geoserver:
    image: jupytepide/geoserver:mvp-final
    container_name: jupyteo-geoserver
    networks:
      - jupyteo-net
    volumes:
    - geoserver-data:/opt/geoserver/data_dir
    ports:
    - "8090:8080"
    hostname: jupyteo-geoserver
    restart: on-failure
    env_file:
    - geoserver.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  mapnik:
    image: "jupytepide/mapnik-flask:1.2.2"
    container_name: jupyteo-mapnik
    networks:
      - jupyteo-net
    ports:
    - "9443:80"
    hostname: jupyteo-mapnik
    volumes:
    - /opt/var/mapnik:/opt/var/mapnik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager

  pywps:
    image: "geocontainers/pywps-demo:latest"
    container_name: jupyteo-pywps
    networks:
      - jupyteo-net
    ports:
      - "5555:5000"
    hostname: jupyteo-pywps
    volumes:
      - /opt/data/pub/shared/pywps-demo/workdir:/pywps-demo/workdir
      - /opt/data/pub/shared/pywps-demo/outputs:/pywps-demo/outputs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager

  portainer:
    image: portainer/portainer
    container_name: jupyteo-portainer
    networks:
      - jupyteo-net
    hostname: jupyteo-portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data


networks:
  jupyteo-net:
    external:
      name: jupyteo-net

volumes:
  db:
    external:
      name: ${DB_VOLUME_DATA}
  nginx_volume:
    external:
      name: ${NGINX_VOLUME_DATA}
  geoserver-data:
    external:
      name: ${GEOSERVER_VOLUME_DATA}
  postgis-db-data:
    external:
      name: ${POSTGIS_VOLUME_DATA}
  portainer-data:
    external:
      name: ${PORTAINER_VOLUME_DATA}