version: "3"
services:
  #  jupytepide-proxy:
  #    env_file: .env
  #    image: jupyterhub/configurable-http-proxy:3.1.1
  #    container_name: jupytepide-proxy
  #    hostname: jupytepide-proxy
  #    networks:
  #    - jupyterhub-net
  #    # expose the proxy to the world
  #    ports:
  #    - "80:8000"
  #    - "443:8000"
  #    command:
  #    - configurable-http-proxy
  #    - '--error-target'
  #    - 'http://jupytepide-hub/hub/error'

  #  docker run \
  #  --cap-add=NET_ADMIN \
  #  --name nginx \
  #  -p 443:443 \
  #  -p 80:80 \
  #  --detach \
  #  -e EMAIL=jupytep@wasat.pl \
  #  # -e URL=jupyteo.com \
  #  -e URL=jupytepide.ga \
  #  -v nginx_volume:/config \
  #  --network jupytepide-swarm-net \
  #  --mount type=bind,src=/home/eouser/jupytep-dev/swarm/letsencrypt_container_nginx.conf,dst=/config/nginx/site-confs/default \
  #  linuxserver/letsencrypt

  jupytepide-hub:
    # build an image with SwarmSpawner and our jupyterhub_config.py
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: "jupytepide/hub"
    container_name: jupytepide-hub
    # mount the docker socket
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - ./jupyterhub_config.py:/tmp/jupyterhub_config.py
    - ./run-from-compose.sh:/run-from-compose.sh
    - /opt/data/priv/:/opt/data/priv/
    networks:
    - jupyterhub-net
    # This is necessary to prevent the singleton hub from using its service number as its hostname
    ports:
    - "8000:8000"
    hostname: jupytepide-hub
    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_SPAWN_NOTEBOOK_IMAGE: ${DOCKER_SPAWN_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
    command: sh /run-from-compose.sh

  nginx:
    env_file: .env
    image: linuxserver/letsencrypt
    container_name: nginx
    hostname: nginx
    networks:
    - jupyterhub-net
    # expose the proxy to the world
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_volume:/config"
    - /home/eouser/jupytep-dev/swarm/letsencrypt_container_nginx.conf:/config/nginx/site-confs/default
    environment:
      EMAIL: ${EMAIL}
      URL: ${URL}
    cap_add:
    - NET_ADMIN

networks:
  jupyterhub-net:
    external:
      name: jupytepide-swarm-net

#networks:
#  jupyterhub-net:
#    driver: overlay

volumes:
  db:
    external:
      name: ${DB_VOLUME_DATA}
  nginx_volume:
    external:
      name: nginx_volume
  geoserver-data:
  postgis-db-data: