version: "3"
services:
  test-pywps-flask:
    image: "jupytepide/pywps-flask:16.0.4-1.3.5"
    container_name: test-pywps-flask
    networks:
      - jupyterhub-net
    ports:
      - "25000:5000"
    hostname: test-pywps-flask
    volumes:
      - /opt/data/pub/shared/pywps-test/pywps-flask/workdir:/pywps-flask/workdir
      - /opt/data/pub/shared/pywps-test/pywps-flask/outputs:/pywps-flask/outputs
      - /opt/data/pub/shared/pywps-test/pywps-flask/processes:/pywps-flask/processes
      - /home/eouser/jupytep-dev/pywps/pywps-flask.cfg:/pywps-flask/pywps.cfg
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  test-pywps-demo:
    image: "jupytepide/pywps-demo:1.3.5"
    container_name: test-pywps-demo
    networks:
      - jupyterhub-net
    ports:
      - "35000:5000"
    hostname: test-pywps-demo
    volumes:
      - /opt/data/pub/shared/pywps-test/pywps-demo/workdir:/pywps-demo/workdir
      - /opt/data/pub/shared/pywps-test/pywps-demo/outputs:/pywps-demo/outputs
      - /opt/data/pub/shared/pywps-test/pywps-demo/processes:/pywps-demo/processes
      - /home/eouser/jupytep-dev/pywps/pywps-demo.cfg:/pywps-demo/pywps.cfg
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
networks:
  jupyterhub-net:
    external:
      name: jupytepide-swarm-net