# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub-db:
    image: postgres:9.5
    container_name: jupytepide-hub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - jupyterhub-base/secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  mapnik:
    image: "jupytepide/tilestache-mapnik:ver_1.0.3"
    container_name: jupytepide-mapnik
    ports:
     - "32798:22"
     - "32799:9001"
     - "32800:80"
    volumes:
     - mapnik:/etc/tilestache

  hub:
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: Dockerfile.jupytepidehub
      args:
        JUPYTEPIDE_HUB_VERSION: ${JUPYTEPIDE_HUB_VERSION}
    restart: always
    image: jupytepide-hub
    container_name: jupytepide-hub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
      - "eodata:${EODATA_VOLUME_CONTAINER}"
      - "mapnik:${MAPNIK_VOLUME_CONTAINER}"
    ports:
      - "443:443"
    links:
      - hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # JupyterHub will spawn this Notebook image for users
      # DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
    env_file:
      - jupyterhub-base/secrets/postgres.env
      - jupyterhub-base/secrets/oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  db:
    external:
      name: ${DB_VOLUME_HOST}
  eodata:
  mapnik:
    external:
      name: ${MAPNIK_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
