version: "3"
services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    container_name: reg-nginx
    networks:
      - jupyteo-net
    hostname: reg-nginx
    ports:
      - 5043:443
    links:
      - registry:registry
    volumes:
      - /reg/registry/security:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro

  registry:
    image: registry:2
    container_name: reg-registry
    volumes:
      - /reg/registry/data:/var/lib/registry
      - /reg/registry/security:/etc/security
    hostname: reg-registry
    networks:
      - jupyteo-net
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /etc/security/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: reg-frontend
    hostname: reg-frontend
    networks:
      - jupyteo-net
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: reg.jupyteo.com
      ENV_DOCKER_REGISTRY_PORT: 443 \
      ENV_DOCKER_REGISTRY_USE_SSL: 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  jupyteo-net:
    external:
      name: jupyteo-net