# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
ARG DOCKER_VER
FROM jupytepide/geospatial-notebook:$DOCKER_VER

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends --allow-unauthenticated file && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

# Download and install ESA SNAP toolbox (with all components)
# Install and configure Snappy
# COPY esa-snap_all_unix_6_0.sh /tmp/esa-snap_all_unix_6_0.sh
RUN wget --quiet http://step.esa.int/downloads/6.0/installers/esa-snap_all_unix_6_0.sh && \
    chmod +x esa-snap_all_unix_6_0.sh && \
    /bin/bash "esa-snap_all_unix_6_0.sh" -q

USER $NB_USER

RUN mkdir .snap && \
    mkdir .snap/snap-python && \
    mkdir .snap/snap-python/snappy && \
    wget --quiet https://github.com/wasat/JupyTEPIDE/raw/dev/libs/jpy-0.9.0-cp36-cp36m-linux_x86_64.whl -P "/home/jovyan/.snap/snap-python/snappy" && \
    cd /opt/snap/bin && \
    ./snappy-conf /opt/conda/bin/python /home/jovyan/.snap/snap-python && \
    rm -rf /home/jovyan/.snap/snap-python/snappy/testdata && \
    cp -R /home/jovyan/.snap/snap-python/snappy /opt/conda/lib/python3.6/site-packages/ && \
    rm -rf /home/jovyan/.snap/snap-python

ENV PATH="/opt/conda/bin:${PATH}"

USER root

# Download and install SnapHu
# Standalone install
WORKDIR /opt
RUN wget --quiet http://step.esa.int/thirdparties/snaphu/1.4.2-2/snaphu-v1.4.2_linux.zip && \
    unzip snaphu-v1.4.2_linux.zip && \
    mv snaphu-v1.4.2_linux snaphu &&\
    chmod 755 snaphu/bin/snaphu &&\
    rm -rf snaphu-v1.4.2_linux*
ENV PATH="/opt/snaphu/bin:${PATH}"

# Download and install Orfeo toolbox OTB
# Standalone install
# COPY OTB-6.6.0-Linux64.run /opt/OTB-6.6.0-Linux64.run
RUN wget --quiet https://www.orfeo-toolbox.org/packages/OTB-6.6.0-Linux64.run && \
    chmod +x OTB-6.6.0-Linux64.run && \
    /bin/bash -c "OTB_PYTHON_EXE=/opt/conda/envs/python27/bin/python2.7 ./OTB-6.6.0-Linux64.run" -q &&\
    rm -rf OTB-6.6.0-Linux64.run

RUN cd /tmp && \
    /bin/bash -c "R -e \"install.packages('devtools', repos='http://cran.cnr.berkeley.edu/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('Rcpp', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('RcppEigen', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('ggplot2', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('Cairo', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('evaluate', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('formatR', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('highr', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('markdown', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('yaml', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('htmltools', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('knitr', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('rmarkdown', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('RColorBrewer', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('sp', repos='http://cran.cnr.berkeley.edu/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('raster', repos='http://cran.cnr.berkeley.edu/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('gstat', repos='http://cran.cnr.berkeley.edu/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('httr', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('githubinstall', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\""  && \
    /bin/bash -c "R -e \"install.packages('magick', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"install.packages('rgdal', repos='http://cran.rstudio.com/', clean = TRUE, quiet = TRUE)\"" && \
    /bin/bash -c "R -e \"library(devtools)\"" && \
    /bin/bash -c "R -e \"options(unzip='internal')\"" && \
    R -e "devtools::install_git(\"https://github.com/gowusu/sebkc.git\", branch = \"master\")" && \
    # wget --quiet https://download2.rstudio.org/rstudio-server-0.99.903-amd64.deb && \
    # gdebi -n rstudio-server-0.99.903-amd64.deb  && \
    find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf

RUN find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    npm cache clean --force && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    fix-permissions "/opt/OTB-6.6.0-Linux64"

WORKDIR /home/$NB_USER
USER $NB_USER